/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/earth.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        name="Icosphere"
        geometry={nodes.Icosphere.geometry}
        material={materials['Material.001']}
        scale={[0.9, 0.9, 0.91]}
      />
      <mesh
        name="Icosphere001"
        geometry={nodes.Icosphere001.geometry}
        material={materials['Material.002']}
        scale={[0.97, 0.97, 0.97]}
      />

      
    </group>
  )
}

useGLTF.preload('/earth.glb')
